const express=require('express');const cors=require('cors');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const crypto=require('crypto');const path=require('path');const fs=require('fs');
const app=express();app.use(cors());app.use(express.json({limit:'20mb'}));
const PORT=Number(process.env.PORT||3000), DB_FILE=process.env.DB_FILE||path.join(__dirname,'xcar.sqlite');
const db=new Database(DB_FILE);db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,email TEXT DEFAULT '',phone TEXT DEFAULT '',subscription_until INTEGER NOT NULL,blocked INTEGER DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,payload TEXT DEFAULT '{}');CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER,created_at INTEGER);CREATE TABLE IF NOT EXISTS subscription_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,username TEXT,name TEXT,phone TEXT,months INTEGER,price INTEGER,status TEXT DEFAULT 'pending',created_at INTEGER,decided_at INTEGER);CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,from_admin INTEGER,message TEXT,created_at INTEGER);`);
const q={userByName:db.prepare('SELECT * FROM users WHERE username=?'), userById:db.prepare('SELECT * FROM users WHERE id=?')};
function hash(p){return bcrypt.hashSync(String(p),12)} function okPass(p,h){return bcrypt.compareSync(String(p),h)} function token(){return crypto.randomBytes(32).toString('hex')} function now(){return Date.now()}
const adminUser=process.env.ADMIN_USER||'admin',adminPass=process.env.ADMIN_PASSWORD||'CHANGE_ME_NOW';
function userAuth(req){const h=req.headers.authorization||'';if(h.startsWith('Bearer ')){const s=db.prepare('SELECT * FROM sessions WHERE token=?').get(h.slice(7));if(s)return q.userById.get(s.user_id)}const b=req.body||{};if(b.username&&b.password){const u=q.userByName.get(b.username);if(u&&okPass(b.password,u.password_hash))return u}return null}
function adminAuth(req){const h=req.headers.authorization||'';return h.startsWith('Basic ')&&Buffer.from(h.slice(6),'base64').toString()===`${adminUser}:${adminPass}`}
app.get('/health',(req,res)=>res.json({ok:true,time:now()}));
app.get('/api/public/subscription',(req,res)=>res.json({monthPrice:Number(process.env.MONTH_PRICE||500),bank:process.env.PAY_BANK||'Сбербанк',cardNumber:process.env.PAY_CARD||'',recipient:process.env.PAY_RECIPIENT||'',phone:process.env.PAY_PHONE||''}));
app.post('/api/register',(req,res)=>{const {username,password,email='',phone='',payload={}}=req.body||{};if(!username||!password)return res.status(400).json({error:'Логин и пароль обязательны'});if(q.userByName.get(username))return res.status(409).json({error:'Такой логин уже существует'});const t=now(),until=t+30*86400000;const info=db.prepare('INSERT INTO users(username,password_hash,email,phone,subscription_until,created_at,updated_at,payload) VALUES(?,?,?,?,?,?,?,?)').run(username,hash(password),email,phone,until,t,t,JSON.stringify(payload||{}));const tok=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(tok,info.lastInsertRowid,t);res.json({ok:true,token:tok,subscriptionUntil:until,updatedAt:t});});
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{},u=q.userByName.get(username);if(!u)return res.status(404).json({error:'Аккаунт не найден'});if(!okPass(password,u.password_hash))return res.status(401).json({error:'Неверный пароль'});if(u.blocked)return res.status(403).json({error:'Пользователь заблокирован'});const tok=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(tok,u.id,now());let payload={};try{payload=JSON.parse(u.payload||'{}')}catch{}res.json({ok:true,token:tok,email:u.email,phone:u.phone,subscriptionUntil:u.subscription_until,updatedAt:u.updated_at,payload});});
app.post('/api/sync',(req,res)=>{const u=userAuth(req);if(!u)return res.status(401).json({error:'auth'});if(u.blocked)return res.status(403).json({error:'blocked'});const payload=req.body.payload||{};const t=now();db.prepare('UPDATE users SET payload=?,updated_at=? WHERE id=?').run(JSON.stringify(payload),t,u.id);let p={};try{p=JSON.parse(u.payload||'{}')}catch{}res.json({ok:true,updatedAt:t,subscriptionUntil:u.subscription_until,payload});});
app.post('/api/subscription/request',(req,res)=>{const u=userAuth(req);if(!u)return res.status(401).json({error:'auth'});const {name='',phone='',months=1,price=500}=req.body||{};const allowed=[1,3,6,12];if(!allowed.includes(Number(months)))return res.status(400).json({error:'invalid months'});const info=db.prepare('INSERT INTO subscription_requests(user_id,username,name,phone,months,price,created_at) VALUES(?,?,?,?,?,?,?)').run(u.id,u.username,name,phone,Number(months),Number(price),now());res.json({ok:true,id:info.lastInsertRowid});});
app.get('/api/account',(req,res)=>{const u=userAuth(req);if(!u)return res.status(401).json({error:'auth'});res.json({id:u.id,username:u.username,email:u.email,phone:u.phone,subscriptionUntil:u.subscription_until,blocked:!!u.blocked});});
app.get('/api/admin/users',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});const users=db.prepare('SELECT id,username,email,phone,subscription_until,blocked,created_at,updated_at FROM users ORDER BY id DESC').all();res.json({users});});
app.get('/api/admin/requests',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});res.json({requests:db.prepare('SELECT * FROM subscription_requests ORDER BY id DESC').all()});});
app.post('/api/admin/users/:id/subscription',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});const u=q.userById.get(req.params.id);if(!u)return res.status(404).json({error:'not found'});const days=Number(req.body.days||0);const until=now()+days*86400000;db.prepare('UPDATE users SET subscription_until=?,updated_at=? WHERE id=?').run(until,now(),u.id);res.json({ok:true,subscriptionUntil:until});});
app.post('/api/admin/requests/:id/decision',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});const r=db.prepare('SELECT * FROM subscription_requests WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'not found'});const status=req.body.status==='approved'?'approved':'rejected';db.prepare('UPDATE subscription_requests SET status=?,decided_at=? WHERE id=?').run(status,now(),r.id);if(status==='approved'){const u=q.userById.get(r.user_id);if(u){const base=Math.max(now(),u.subscription_until);const until=base+r.months*30*86400000;db.prepare('UPDATE users SET subscription_until=?,updated_at=? WHERE id=?').run(until,now(),u.id)}}res.json({ok:true});});
app.post('/api/admin/users/:id/block',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});db.prepare('UPDATE users SET blocked=?,updated_at=? WHERE id=?').run(req.body.blocked?1:0,now(),req.params.id);res.json({ok:true});});
app.delete('/api/admin/users/:id',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});db.prepare('DELETE FROM users WHERE id=?').run(req.params.id);res.json({ok:true});});
app.post('/api/admin/message',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});const {userId,message}=req.body||{};db.prepare('INSERT INTO messages(user_id,from_admin,message,created_at) VALUES(?,?,?,?)').run(userId,1,String(message||''),now());res.json({ok:true});});
app.get('/api/admin/messages/:userId',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});res.json({messages:db.prepare('SELECT * FROM messages WHERE user_id=? ORDER BY id').all(req.params.userId)});});
app.get('/api/admin/backup',(req,res)=>{if(!adminAuth(req))return res.status(401).json({error:'admin auth'});const stamp=new Date().toISOString().replace(/[:.]/g,'-');const out=path.join(__dirname,`backup-${stamp}.sqlite`);db.pragma('wal_checkpoint(TRUNCATE)');fs.copyFileSync(DB_FILE,out);res.download(out,`xcar-backup-${stamp}.sqlite`,()=>{try{fs.unlinkSync(out)}catch{}});});
app.listen(PORT,()=>console.log(`XCAR server listening on ${PORT}`));
